### ISSUE TITLE
直播崩溃

### ISSUE THREAD

**Issue by yunboxtvj** [XiaoRanLiu3119/TVBoxOS-Mobile#26]
直播左边的退出键，按退出键软件就崩溃。

Build version: 0.4 
Build date: 2023-10-12 19:30:16 
Current date: 2023-10-12 20:41:22 
Device: HUAW
OS version: Android 10 (SDK 29) 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void xyz.doikki.videoplayer.player.VideoView.v()' on a null object reference
	at com.github.tvbox.osc.ui.activity.LivePlayActivity.m1(SourceFile:802)
	at com.github.tvbox.osc.ui.activity.LivePlayActivity.o1(SourceFile:850)
	at com.github.tvbox.osc.ui.activity.LivePlayActivity$m.run(SourceFile:1254)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

User actions: 
2023-10-12 20:35:31: MainActivity created
2023-10-12 20:35:31: MainActivity resumed
2023-10-12 20:35:37: MainActivity paused
2023-10-12 20:35:37: SettingActivity created
2023-10-12 20:35:37: SettingActivity resumed
2023-10-12 20:35:53: SettingActivity paused
2023-10-12 20:35:56: SettingActivity resumed
2023-10-12 20:36:02: SettingActivity paused
2023-10-12 20:39:45: SettingActivity resumed
2023-10-12 20:39:48: SettingActivity paused
2023-10-12 20:39:48: MainActivity resumed
2023-10-12 20:39:49: SettingActivity destroyed
2023-10-12 20:39:51: MainActivity paused
2023-10-12 20:39:51: LivePlayActivity created
2023-10-12 20:39:51: LivePlayActivity resumed
2023-10-12 20:40:09: LivePlayActivity paused
2023-10-12 20:40:16: LivePlayActivity resumed
2023-10-12 20:40:38: LivePlayActivity paused
2023-10-12 20:40:38: MainActivity resumed
2023-10-12 20:40:38: LivePlayActivity destroyed

**Comment by XiaoRanLiu3119** [comment]
直播左边没退出键呢，右边的退出？试试我新打的包呢
