### ISSUE TITLE
竖屏下在线字幕搜索栏异常

### ISSUE THREAD

**Issue by M17764017422** [XiaoRanLiu3119/TVBoxOS-Mobile#44]
```
Build version: 1.0.0 
Current date: 2023-11-05 00:51:21 
Device: Xiaomi M2007
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.NullPointerException: url == null
	at okhttp3.Request$Builder.url(SourceFile:156)
	at androidx.base.t20.f(SourceFile:198)
	at androidx.base.t20.e(SourceFile:49)
	at androidx.base.yy.t(SourceFile:218)
	at androidx.base.yy.k(SourceFile:39)
	at androidx.base.vy.a(SourceFile:103)
	at androidx.base.zm.Y(SourceFile:987)
	at androidx.base.zm$c.onClick(SourceFile:966)
	at android.view.View.performClick(View.java:7753)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29146)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

User actions: 
2023-11-05 00:41:53: MainActivity created
2023-11-05 00:41:53: MainActivity resumed
2023-11-05 00:42:28: MainActivity paused
2023-11-05 00:42:28: LiveActivity created
2023-11-05 00:42:28: MainActivity resumed
2023-11-05 00:42:28: LiveActivity destroyed
2023-11-05 00:42:29: MainActivity paused
2023-11-05 00:42:29: LiveActivity created
2023-11-05 00:42:29: MainActivity resumed
2023-11-05 00:42:30: LiveActivity destroyed
2023-11-05 00:42:31: MainActivity paused
2023-11-05 00:42:31: LiveActivity created
2023-11-05 00:42:31: MainActivity resumed
2023-11-05 00:42:31: LiveActivity destroyed
2023-11-05 00:42:37: MainActivity paused
2023-11-05 00:42:37: SettingActivity created
2023-11-05 00:42:37: SettingActivity resumed
2023-11-05 00:43:31: MainActivity destroyed
2023-11-05 00:43:31: SettingActivity paused
2023-11-05 00:43:31: MainActivity created
2023-11-05 00:43:31: MainActivity resumed
2023-11-05 00:43:32: SettingActivity destroyed
2023-11-05 00:43:38: MainActivity paused
2023-11-05 00:43:38: HistoryActivity created
2023-11-05 00:43:38: HistoryActivity resumed
2023-11-05 00:43:41: HistoryActivity paused
2023-11-05 00:43:41: MainActivity resumed
2023-11-05 00:43:42: HistoryActivity destroyed
2023-11-05 00:45:08: MainActivity paused
2023-11-05 00:45:08: MainActivity created
2023-11-05 00:45:08: MainActivity resumed
2023-11-05 00:45:34: MainActivity paused
2023-11-05 00:45:34: LiveActivity created
2023-11-05 00:45:34: LiveActivity resumed
2023-11-05 00:45:50: LiveActivity paused
2023-11-05 00:45:50: MainActivity resumed
2023-11-05 00:45:50: LiveActivity destroyed
2023-11-05 00:46:20: MainActivity paused
2023-11-05 00:46:20: FastSearchActivity created
2023-11-05 00:46:20: FastSearchActivity resumed
2023-11-05 00:46:44: FastSearchActivity paused
2023-11-05 00:46:44: DetailActivity created
2023-11-05 00:46:44: DetailActivity resumed

```

**Comment by M17764017422** [comment]
https://github.com/XiaoRanLiu3119/TVBoxOS-Mobile/assets/31874069/22bc9f01-3086-4317-9ed7-f989387f3f72

搜索栏显示不全，无法调出键盘

**Comment by XiaoRanLiu3119** [comment]
崩溃的源和哪个影视发下我复现看看

**Comment by M17764017422** [comment]
饭太硬.top，大概是个网盘搜索，应该和源无关吧？是在搜索在线字幕的时候出现的

**Comment by M17764017422** [comment]
> 崩溃的源和哪个影视发下我复现看看

```
Build version: 1.0.0 
Current date: 2023-11-06 00:45:00 
Device: Xiaomi M2007J3SC 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.NullPointerException: url == null
	at okhttp3.Request$Builder.url(SourceFile:156)
	at androidx.base.t20.f(SourceFile:198)
	at androidx.base.t20.e(SourceFile:49)
	at androidx.base.yy.t(SourceFile:218)
	at androidx.base.yy.k(SourceFile:39)
	at androidx.base.vy.a(SourceFile:103)
	at androidx.base.zm.Y(SourceFile:987)
	at androidx.base.zm$c.onClick(SourceFile:966)
	at android.view.View.performClick(View.java:7753)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29146)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

User actions: 
2023-11-06 00:35:38: MainActivity created
2023-11-06 00:35:39: MainActivity resumed
2023-11-06 00:35:55: MainActivity paused
2023-11-06 00:36:06: MainActivity resumed
2023-11-06 00:36:10: MainActivity paused
2023-11-06 00:37:13: MainActivity resumed
2023-11-06 00:37:33: MainActivity paused
2023-11-06 00:37:33: FastSearchActivity created
2023-11-06 00:37:33: FastSearchActivity resumed
2023-11-06 00:37:43: FastSearchActivity paused
2023-11-06 00:37:43: DetailActivity created
2023-11-06 00:37:43: DetailActivity resumed
2023-11-06 00:41:31: DetailActivity paused
2023-11-06 00:41:32: FastSearchActivity resumed
2023-11-06 00:41:41: FastSearchActivity paused
2023-11-06 00:41:41: DetailActivity resumed

```

**Comment by M17764017422** [comment]
> 崩溃的源和哪个影视发下我复现看看
复现方法找到了，重复加载同一在线字幕三次绝对崩溃，本地字幕没试过不知道。

```
Build version: 1.0.0 
Current date: 2023-11-06 01:46:01 
Device: Xiaomi M2007
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.NullPointerException: url == null
	at okhttp3.Request$Builder.url(SourceFile:156)
	at androidx.base.t20.f(SourceFile:198)
	at androidx.base.t20.e(SourceFile:49)
	at androidx.base.yy.t(SourceFile:218)
	at androidx.base.yy.k(SourceFile:39)
	at androidx.base.vy.a(SourceFile:103)
	at androidx.base.zm.Y(SourceFile:987)
	at androidx.base.zm$c.onClick(SourceFile:966)
	at android.view.View.performClick(View.java:7753)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29146)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

User actions: 
2023-11-06 01:42:48: MainActivity created
2023-11-06 01:42:48: MainActivity resumed
2023-11-06 01:43:12: MainActivity paused
2023-11-06 01:43:12: FastSearchActivity created
2023-11-06 01:43:12: FastSearchActivity resumed
2023-11-06 01:43:16: FastSearchActivity paused
2023-11-06 01:43:16: DetailActivity created
2023-11-06 01:43:16: DetailActivity resumed

```

**Comment by M17764017422** [comment]
对于我来说更加影响使用的问题还是字幕搜索栏显示不全导致无法调出键盘

**Comment by XiaoRanLiu3119** [comment]
> 对于我来说更加影响使用的问题还是字幕搜索栏显示不全导致无法调出键盘

好的,在下版修复下

**Comment by XiaoRanLiu3119** [comment]
> 饭太硬.top，大概是个网盘搜索，应该和源无关吧？是在搜索在线字幕的时候出现的

哪个影视发我下,我找了在用的没有在线字幕

**Comment by M17764017422** [comment]
就是搜索字幕后，选择同一个字幕文件，重复搜索、选择，加载三次，可能是我之前的表述不够明确引发了误解，我一般用易搜和玩偶哥哥比较多，不过我测试了所有源都一样包括非网盘源
如果还是无法复现我发视频，有QQ吗，这里限制10M每次都要剪辑压缩太麻烦

**Comment by XiaoRanLiu3119** [comment]
行,大概了解了,后续我试下

**Comment by XiaoRanLiu3119** [comment]
改好了,全屏搜不遮挡的话先对付用,或者会打包可以自己打。有其他改动下版一起发
