### ISSUE TITLE
设置播放链接报错

### ISSUE THREAD

**Issue by jjjzcyt** [XiaoRanLiu3119/TVBoxOS-Mobile#65]
测试了一下，泥视频的播放当前页面链接和下载链接都报错。另外作者能把视频复制链接按钮添加上吗，我没用idm下载。

**Comment by XiaoRanLiu3119** [comment]
播放当前页面链接报错是啥意思，报错信息有么，或者那个接口有泥视频我看看

**Comment by jjjzcyt** [comment]
> 播放当前页面链接报错是啥意思，报错信息有么，或者那个接口有泥视频我看看
是在我的界面播放链接选项报错
Build version: 1.0.3 
Current date: 2023-11-25 10:04:14 
Device: Xiaomi 22081212C 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.tvbox.osc/com.github.tvbox.osc.ui.activity.DetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.tvbox.osc.bean.SourceBean.getType()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.tvbox.osc.bean.SourceBean.getType()' on a null object reference
	at com.github.tvbox.osc.ui.activity.DetailActivity.p(SourceFile:7)
	at com.github.tvbox.osc.ui.activity.DetailActivity.init(SourceFile:37)
	at com.github.tvbox.osc.base.BaseActivity.onCreate(SourceFile:21)
	at android.app.Activity.performCreate(Activity.java:8516)
	at android.app.Activity.performCreate(Activity.java:8480)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3803)
	... 12 more

User actions: 
2023-11-25 10:00:36: MainActivity created
2023-11-25 10:00:36: MainActivity resumed
2023-11-25 10:00:42: MainActivity paused
2023-11-25 10:00:42: SubscriptionActivity created
2023-11-25 10:00:42: SubscriptionActivity resumed
2023-11-25 10:00:47: SubscriptionActivity paused
2023-11-25 10:00:57: SubscriptionActivity resumed
2023-11-25 10:00:58: SubscriptionActivity paused
2023-11-25 10:01:05: SubscriptionActivity resumed
2023-11-25 10:01:09: SubscriptionActivity paused
2023-11-25 10:01:31: SubscriptionActivity resumed
2023-11-25 10:02:08: SubscriptionActivity paused
2023-11-25 10:02:23: SubscriptionActivity resumed
2023-11-25 10:02:43: SubscriptionActivity paused
2023-11-25 10:02:43: MainActivity created
2023-11-25 10:02:43: MainActivity resumed
2023-11-25 10:02:43: SubscriptionActivity destroyed
2023-11-25 10:02:54: MainActivity paused
2023-11-25 10:02:54: SubscriptionActivity created
2023-11-25 10:02:54: SubscriptionActivity resumed
2023-11-25 10:02:58: SubscriptionActivity paused
2023-11-25 10:03:01: SubscriptionActivity resumed
2023-11-25 10:03:03: SubscriptionActivity paused
2023-11-25 10:03:24: SubscriptionActivity resumed
2023-11-25 10:03:40: SubscriptionActivity paused
2023-11-25 10:03:40: MainActivity resumed
2023-11-25 10:03:41: SubscriptionActivity destroyed
2023-11-25 10:03:41: MainActivity paused
2023-11-25 10:03:58: MainActivity resumed
2023-11-25 10:04:02: MainActivity paused
2023-11-25 10:04:02: MainActivity resumed
2023-11-25 10:04:09: MainActivity paused
2023-11-25 10:04:09: DetailActivity created

**Comment by XiaoRanLiu3119** [comment]
看着是源的问题，如有其他包括泥视频的源可以试试

**Comment by jjjzcyt** [comment]
> 看着是源的问题，如有其他包括泥视频的源可以试试

同一个视频链接在realme手机上可以播放，不会报错。

**Comment by jjjzcyt** [comment]
> 看着是源的问题，如有其他包括泥视频的源可以试试

同一个视频链接在realme手机上可以播放不会报错，系统是安卓11。

**Comment by XiaoRanLiu3119** [comment]
不清楚啦，我这复现不了，碰着再修

**Comment by jllyzjs** [comment]
从有这个功能，就提示错误重启，试过N多次和源。

**Comment by XiaoRanLiu3119** [comment]
> 从有这个功能，就提示错误重启，试过N多次和源。

用的少，没用到的可能不知道，报错的源和如何操作的发下我明天试试

**Comment by XiaoRanLiu3119** [comment]
自测了下，泥视频嗅探到的链接可正常通过设置链接播放

https://api.nivodz.com/play/mud.m3u8/WAP/1.0?ce=9fb13568902927b95a02825f88b1373d9ed41cd53919a9733bc5ab04b92896b1938daebbaaf09903c93cae38076e8c44e1fbde5dc3c9230d964a7a9184f8d22719de22fa68a9a442777389c04daab0e1a82321d4d0ff6496&pf=4&uk=cb715e29aa0392ac48d36d54f464eb62&rx=7990&expire=1703195408632&ip=38.207.141.227&sign=7d9d17de2ffd6a64109e474639792edd&_ts=1703170208632

**Comment by jllyzjs** [comment]
<iframe frameborder="0" src="https://cloud.lxweb.cn/f/bGD7Up/SVID_20231222_095701_1.mp4" allowFullScreen="true"></iframe>

**Comment by XiaoRanLiu3119** [comment]
可以清除全部数据或卸载重装试试,我小米是安卓13正常,哪天再搞些其他设备试试
